
import { Level, Achievement } from './types';

export const LEVELS: Level[] = [
  { name: "Plankton", min: 0, description: "Tiny but mighty! You're the foundation of the ocean ecosystem.", graphic: "plankton", emoji: "" },
  { name: "Krill", min: 500, description: "A bit bigger, but still whale food. Keep growing!", graphic: "krill", emoji: "" },
  { name: "Sea Snail", min: 1000, description: "Slow and steady wins the race! You're making your mark on the ocean floor.", graphic: "seasnail", emoji: "" },
  { name: "Sardine", min: 1500, description: "You're starting to school the competition!", graphic: "sardine", emoji: "" },
  { name: "Seahorse", min: 2000, description: "Galloping through those questions with grace.", graphic: "seahorse", emoji: "" },
  { name: "Squid", min: 2500, description: "You're inking your way through the tough stuff. Very clever!", graphic: "squid", emoji: "" },
  { name: "Pufferfish", min: 3000, description: "You're puffing up with knowledge! Don't let the pressure get to you.", graphic: "pufferfish", emoji: "" },
  { name: "Flying Fish", min: 3500, description: "You're soaring above the surface now!", graphic: "flyingfish", emoji: "" },
  { name: "Jellyfish", min: 4000, description: "You're glowing with knowledge! Your stinging intellect is paralyzing the competition.", graphic: "jellyfish", emoji: "" },
  { name: "Barracuda", min: 4500, description: "Sharp mind, sharp teeth. You're a predator now.", graphic: "barracuda", emoji: "" },
  { name: "Stingray", min: 5000, description: "Gliding effortlessly through the deep. You're a majestic force!", graphic: "stingray", emoji: "" },
  { name: "Dolphin", min: 5500, description: "You're the smartest mammal in the sea! Your playful yet focused approach is making waves.", graphic: "dolphin", emoji: "" },
  { name: "Orca", min: 6000, description: "A brilliant tactician of the sea. You're dominating the question bank!", graphic: "orca", emoji: "" },
  { name: "Great White Shark", min: 6500, description: "The apex predator of Step 2. Terrifyingly smart!", graphic: "shark", emoji: "" },
  { name: "Blue Whale", min: 7000, description: "You are a literal giant of medicine!", graphic: "whale", emoji: "" },
];

export const LEVEL_VARIANTS: Record<string, string[]> = {
  plankton: ['plankton', 'planktonhat', 'partyplankton'],
  krill: ['krill', 'karatekrill'],
  seasnail: ['seasnail', 'snazzysnail'],
  sardine: ['sardine', 'ceosardine'],
  seahorse: ['seahorse', 'harpisthorse'],
  squid: ['squid', 'squaredancersquid'],
  pufferfish: ['pufferfish', 'punkpuffer'],
  flyingfish: ['flyingfish', 'fighterfish'],
  jellyfish: ['jellyfish', 'jugglingjelly'],
  barracuda: ['barracuda', 'bikerbarracuda'],
  stingray: ['stingray', 'racerray'],
  dolphin: ['dolphin', 'doctordolfo'],
  orca: ['orca', 'operaorca'],
  shark: ['shark', 'sheriffshark'],
  whale: ['whale', 'warriorwhale']
};

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'plankton',
    title: 'Level 1 Plankton',
    image: 'plankton',
    achievementDescription: 'You got started!',
    requirementDescription: 'Must open the app.',
    extraSillyDescription: "Tiny but mighty! You're the foundation of the ocean ecosystem.",
    isAchieved: () => true,
  },
  {
    id: 'sunkenpocketwatch',
    title: 'The Sunken Pocket Watch',
    image: 'pocketwatch',
    achievementDescription: "You've completed 1 practice test!",
    requirementDescription: 'Must complete 1 practice test.',
    extraSillyDescription: "It's technically right twice a day, provided you're in a time zone where the numbers have been replaced by tiny, confused barnacles.",
    isAchieved: () => false,
  },
  {
    id: 'glowdarkcompass',
    title: 'The Glow-in-the-Dark Compass',
    image: 'compass',
    achievementDescription: "You've completed 2 practice tests!",
    requirementDescription: 'Must complete 2 practice tests.',
    extraSillyDescription:
      'It points North, but only if "North" is currently where the nearest snacks are located. Also doubles as a very dim disco ball for lonely shrimp.',
    isAchieved: () => false,
  },
  {
    id: 'admiralsepaulets',
    title: "The Admiral's Epaulets",
    image: 'epaulets',
    achievementDescription: "You've completed 3 practice tests!",
    requirementDescription: 'Must complete 3 practice tests.',
    extraSillyDescription:
      "These gold-fringed shoulder pads make you look very important, even if you're just a sardine who's lost his car keys.",
    isAchieved: () => false,
  },
  {
    id: 'obsidiananchor',
    title: 'The Obsidian Anchor',
    image: 'anchor',
    achievementDescription: "You've completed 4 practice tests!",
    requirementDescription: 'Must complete 4 practice tests.',
    extraSillyDescription:
      'Carved from volcanic glass and surprisingly heavy. It\'s perfect for staying in one place, or for looking very "edgy" at the bottom of a trench.',
    isAchieved: () => false,
  },
  {
    id: 'prismoftheabyss',
    title: 'The Prism of the Abyss',
    image: 'prism',
    achievementDescription: "You've completed 5 practice tests!",
    requirementDescription: 'Must complete 5 practice tests.',
    extraSillyDescription:
      "This giant diamond turns every beam of light into a rainbow. It's lovely to look at, but it makes it very hard for a secret agent squid to hide in the shadows.",
    isAchieved: () => false,
  },
  {
    id: 'tridentofthetideturner',
    title: 'The Trident of the Tide-Turner',
    image: 'trident',
    achievementDescription: "You've completed 6 practice tests!",
    requirementDescription: 'Must complete 6 practice tests.',
    extraSillyDescription:
      'A massive gold fork for the most ambitious of diners. It can control the ocean currents, or at the very least, poke a very large potato from quite a distance.',
    isAchieved: () => false,
  },
  {
    id: 'livingcoralcrown',
    title: 'The Living Coral Crown',
    image: 'crown',
    achievementDescription: "You've completed 7 practice tests!",
    requirementDescription: 'Must complete 7 practice tests.',
    extraSillyDescription:
      "It's a regal symbol of power that occasionally tries to walk off your head to go find a nice sunny spot on a rock.",
    isAchieved: () => false,
  },
  {
    id: 'planktonhat',
    title: "Plankton's Hat",
    image: 'planktonhat',
    achievementDescription: '100 XP earned!',
    requirementDescription: 'Earn 100 total XP.',
    extraSillyDescription: "Plankton's been looking for this!",
    isAchieved: (total) => total >= 100,
  },
  {
    id: 'partyplankton',
    title: 'Party Plankton',
    image: 'partyplankton',
    achievementDescription: '350 XP earned!',
    requirementDescription: 'Earn 350 total XP.',
    extraSillyDescription: "He's surprisingly loud for someone who's mostly water and confetti.",
    isAchieved: (total) => total >= 350,
  },
  {
    id: 'krill',
    title: 'Level 2 Krill',
    image: 'krill',
    achievementDescription: '500 total XP!',
    requirementDescription: 'Reach Level 2 (500 XP).',
    extraSillyDescription: "You've grown from a speck to a Krill! Watch out for whales!",
    isAchieved: (total) => total >= 500,
  },
  {
    id: 'karatekrill',
    title: 'Karate Krill',
    image: 'karatekrill',
    achievementDescription: '750 XP earned!',
    requirementDescription: 'Earn 750 total XP.',
    extraSillyDescription: "Careful! He's mastered the legendary \"Crouching Shrimp, Hidden Pebble\" technique.",
    isAchieved: (total) => total >= 750,
  },
  {
    id: 'seasnail',
    title: 'Level 3 Sea Snail',
    image: 'seasnail',
    achievementDescription: '1,000 total XP!',
    requirementDescription: 'Reach Level 3 (1,000 XP).',
    extraSillyDescription: "You're now a Sea Snail! Slow and steady wins the race!",
    isAchieved: (total) => total >= 1000,
  },
  {
    id: 'snazzysnail',
    title: 'Snazzy Snail',
    image: 'snazzysnail',
    achievementDescription: '1,250 XP earned!',
    requirementDescription: 'Earn 1,250 total XP.',
    extraSillyDescription: "It takes him four hours to get ready, but the tie is always perfectly straight.",
    isAchieved: (total) => total >= 1250,
  },
  {
    id: 'sardine',
    title: 'Level 4 Sardine',
    image: 'sardine',
    achievementDescription: '1,500 total XP!',
    requirementDescription: 'Reach Level 4 (1,500 XP).',
    extraSillyDescription: "You're now a Sardine! You've joined the school of winners!",
    isAchieved: (total) => total >= 1500,
  },
  {
    id: 'ceosardine',
    title: 'CEO Sardine',
    image: 'ceosardine',
    achievementDescription: '1,750 XP earned!',
    requirementDescription: 'Earn 1,750 total XP.',
    extraSillyDescription: "He's very busy. He has three conference calls and a lunch meeting with a very large tuna.",
    isAchieved: (total) => total >= 1750,
  },
  {
    id: 'seahorse',
    title: 'Level 5 Seahorse',
    image: 'seahorse',
    achievementDescription: '2,000 total XP!',
    requirementDescription: 'Reach Level 5 (2,000 XP).',
    extraSillyDescription: "Giddy up! You're now a Seahorse, galloping toward success!",
    isAchieved: (total) => total >= 2000,
  },
  {
    id: 'harpisthorse',
    title: 'Harpist Horse',
    image: 'harpisthorse',
    achievementDescription: '2,250 XP earned!',
    requirementDescription: 'Earn 2,250 total XP.',
    extraSillyDescription: "It's a bit tricky to play with fins, but the acoustics in the kelp forest are lovely.",
    isAchieved: (total) => total >= 2250,
  },
  {
    id: 'squid',
    title: 'Level 6 Squid',
    image: 'squid',
    achievementDescription: '2,500 total XP!',
    requirementDescription: 'Reach Level 6 (2,500 XP).',
    extraSillyDescription: "You're now a Squid! Inking your way through the tough stuff!",
    isAchieved: (total) => total >= 2500,
  },
  {
    id: 'squaredancersquid',
    title: 'Square Dancer Squid',
    image: 'squaredancersquid',
    achievementDescription: '2,750 XP earned!',
    requirementDescription: 'Earn 2,750 total XP.',
    extraSillyDescription: "Allemande left with your left-left-left tentacle!",
    isAchieved: (total) => total >= 2750,
  },
  {
    id: 'pufferfish',
    title: 'Level 7 Pufferfish',
    image: 'pufferfish',
    achievementDescription: '3,000 total XP!',
    requirementDescription: 'Reach Level 7 (3,000 XP).',
    extraSillyDescription: "You're now a Pufferfish! Puffing up with knowledge!",
    isAchieved: (total) => total >= 3000,
  },
  {
    id: 'punkpuffer',
    title: 'Punk Puffer',
    image: 'punkpuffer',
    achievementDescription: '3,250 XP earned!',
    requirementDescription: 'Earn 3,250 total XP.',
    extraSillyDescription: "He was a rebel until he accidentally poked his own safety pin.",
    isAchieved: (total) => total >= 3250,
  },
  {
    id: 'flyingfish',
    title: 'Level 8 Flying Fish',
    image: 'flyingfish',
    achievementDescription: '3,500 total XP!',
    requirementDescription: 'Reach Level 8 (3,500 XP).',
    extraSillyDescription: "You've taken flight! You're now a Flying Fish, soaring above the rest!",
    isAchieved: (total) => total >= 3500,
  },
  {
    id: 'fighterfish',
    title: 'Fighter Fish',
    image: 'fighterfish',
    achievementDescription: '3,750 XP earned!',
    requirementDescription: 'Earn 3,750 total XP.',
    extraSillyDescription: "Roger that. Requesting permission to buzzy-buzz the reef.",
    isAchieved: (total) => total >= 3750,
  },
  {
    id: 'jellyfish',
    title: 'Level 9 Jellyfish',
    image: 'jellyfish',
    achievementDescription: '4,000 total XP!',
    requirementDescription: 'Reach Level 9 (4,000 XP).',
    extraSillyDescription: "You're now a Jellyfish! You're glowing with knowledge!",
    isAchieved: (total) => total >= 4000,
  },
  {
    id: 'jugglingjelly',
    title: 'Juggling Jelly',
    image: 'jugglingjelly',
    achievementDescription: '4,250 XP earned!',
    requirementDescription: 'Earn 4,250 total XP.',
    extraSillyDescription: "He's doing great, but honestly, having eight arms is basically cheating.",
    isAchieved: (total) => total >= 4250,
  },
  {
    id: 'barracuda',
    title: 'Level 10 Barracuda',
    image: 'barracuda',
    achievementDescription: '4,500 total XP!',
    requirementDescription: 'Reach Level 10 (4,500 XP).',
    extraSillyDescription: "Watch out! You're now a Barracuda, the sharpest mind in the sea!",
    isAchieved: (total) => total >= 4500,
  },
  {
    id: 'bikerbarracuda',
    title: 'Biker Barracuda',
    image: 'bikerbarracuda',
    achievementDescription: '4,750 XP earned!',
    requirementDescription: 'Earn 4,750 total XP.',
    extraSillyDescription: "He's looking for a leather jacket that won't get soggy. It's a real struggle.",
    isAchieved: (total) => total >= 4750,
  },
  {
    id: 'stingray',
    title: 'Level 11 Stingray',
    image: 'stingray',
    achievementDescription: '5,000 total XP!',
    requirementDescription: 'Reach Level 11 (5,000 XP).',
    extraSillyDescription: "You're now a Stingray! Gliding effortlessly through the deep!",
    isAchieved: (total) => total >= 5000,
  },
  {
    id: 'racerray',
    title: 'Racer Ray',
    image: 'racerray',
    achievementDescription: '5,250 XP earned!',
    requirementDescription: 'Earn 5,250 total XP.',
    extraSillyDescription: "He's very aerodynamic, provided he doesn't get distracted by a nice patch of sand.",
    isAchieved: (total) => total >= 5250,
  },
  {
    id: 'dolphin',
    title: 'Level 12 Dolphin',
    image: 'dolphin',
    achievementDescription: '5,500 total XP!',
    requirementDescription: 'Reach Level 12 (5,500 XP).',
    extraSillyDescription: "You're now a Dolphin! You're the smartest mammal in the sea!",
    isAchieved: (total) => total >= 5500,
  },
  {
    id: 'doctordolfo',
    title: 'Doctor Dolfo',
    image: 'doctordolfo',
    achievementDescription: '5,750 XP earned!',
    requirementDescription: 'Earn 5,750 total XP.',
    extraSillyDescription: "He'll see you now. He prescribes three fish and a very long nap.",
    isAchieved: (total) => total >= 5750,
  },
  {
    id: 'orca',
    title: 'Level 13 Orca',
    image: 'orca',
    achievementDescription: '6,000 total XP!',
    requirementDescription: 'Reach Level 13 (6,000 XP).',
    extraSillyDescription: "You're now an Orca! A brilliant tactician of the sea!",
    isAchieved: (total) => total >= 6000,
  },
  {
    id: 'operaorca',
    title: 'Opera Orca',
    image: 'operaorca',
    achievementDescription: '6,250 XP earned!',
    requirementDescription: 'Earn 6,250 total XP.',
    extraSillyDescription: "You haven't lived until you've heard \"O Mio Babbino Caro\" performed in sonar.",
    isAchieved: (total) => total >= 6250,
  },
  {
    id: 'shark',
    title: 'Level 14 Great White Shark',
    image: 'shark',
    achievementDescription: '6,500 total XP!',
    requirementDescription: 'Reach Level 14 (6,500 XP).',
    extraSillyDescription: "Jaws-dropping! You're now a Great White Shark, the master of the deep!",
    isAchieved: (total) => total >= 6500,
  },
  {
    id: 'sheriffshark',
    title: 'Sheriff Shark',
    image: 'sheriffshark',
    achievementDescription: '6,750 XP earned!',
    requirementDescription: 'Earn 6,750 total XP.',
    extraSillyDescription: "This ocean ain't big enough for the two of us... mostly because he takes up half of it.",
    isAchieved: (total) => total >= 6750,
  },
  {
    id: 'whale',
    title: 'Level 15 Blue Whale',
    image: 'whale',
    achievementDescription: '7,000 total XP!',
    requirementDescription: 'Reach Level 15 (7,000 XP).',
    extraSillyDescription: "Incredible! You're now a Blue Whale, a literal giant of medicine!",
    isAchieved: (total) => total >= 7000,
  },
  {
    id: 'warriorwhale',
    title: 'Warrior Whale',
    image: 'warriorwhale',
    achievementDescription: '7,250 XP earned!',
    requirementDescription: 'Earn 7,250 total XP.',
    extraSillyDescription: "His shield is a manhole cover and his courage is infinite. Also, he's hungry.",
    isAchieved: (total) => total >= 7250,
  },
  {
    id: 'steadyswimmer',
    title: 'The Steady Swimmer',
    image: 'steadyswimmer',
    achievementDescription: '3-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions 3 days in a row.',
    extraSillyDescription: "You're just getting started!",
    isAchieved: () => false,
  },
  {
    id: 'highfivefin',
    title: 'High-Five Fin',
    image: 'highfivefin',
    achievementDescription: '5-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions 5 days in a row.',
    extraSillyDescription: "First week down!",
    isAchieved: () => false,
  },
  {
    id: 'tenacioustraveler',
    title: 'The Tenacious Traveler',
    image: 'tenacioustraveler',
    achievementDescription: '10-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions per day for 10 total days.',
    extraSillyDescription: "You've found your rhythm.",
    isAchieved: () => false,
  },
  {
    id: 'torrenttamer',
    title: 'The Torrent Tamer',
    image: 'torrenttamer',
    achievementDescription: '20-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions per day for 20 total days.',
    extraSillyDescription: "Nothing can stop you now.",
    isAchieved: () => false,
  },
  {
    id: 'silverspawner',
    title: 'The Silver Spawner',
    image: 'silverspawner',
    achievementDescription: '30-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions per day for 30 total days.',
    extraSillyDescription: "A month of mastery.",
    isAchieved: () => false,
  },
  {
    id: 'streamsovereign',
    title: 'The Stream Sovereign',
    image: 'streamsovereign',
    achievementDescription: '40-Day Streak!',
    requirementDescription: 'Must complete at least 10 questions per day for 40 total days.',
    extraSillyDescription: "Absolute legend.",
    isAchieved: () => false,
  }
];

export const SILLY_STATEMENTS: Record<string, { moderate: string[], high: string[], levelUp: string }> = {
  "Plankton": {
    moderate: [
      "Just a tiny speck, but you're doing great!",
      "Drifting along nicely, little plankton!",
      "Microscopic progress is still progress!",
      "You're the base of the food chain! Solid start.",
      "Keep floating, you're doing swimmingly!",
      "Small but mighty study session!",
      "Plankton power! You're starting to glow.",
      "Tiny bubbles of knowledge are forming!",
      "You're a microscopic genius in the making!",
      "Feeding the ocean of your mind!"
    ],
    high: [
      "Whoa! This plankton is growing fast!",
      "You're the most productive plankton in the sea!",
      "A bloom of brilliance! You're everywhere!",
      "Plankton-tastic! You're crushing it!",
      "You're out-drifting all the other microbes!",
      "So much energy for such a tiny guy!",
      "You're basically a super-organism now!",
      "The foundation is strong with this one!",
      "You're making a huge splash for a small fry!",
      "Plankton peak performance achieved!"
    ],
    levelUp: "Tiny but mighty! You're the foundation of the ocean ecosystem."
  },
  "Krill": {
    moderate: [
      "Krill-ing it! Keep those questions coming.",
      "A little bigger, a little smarter!",
      "You're not just whale food anymore!",
      "Swimming in the right direction, Krill!",
      "Krill power! You're on a roll.",
      "Small shrimp, big brain!",
      "You're a krill-iant student!",
      "Keep snapping those questions up!",
      "A swarm of success is coming your way!",
      "Krill-ax, you've got this!"
    ],
    high: [
      "You're the king of the krill swarm!",
      "Whales are jealous of your study habits!",
      "Krill-tastic! You're unstoppable today!",
      "You're growing into a real contender!",
      "The ocean is noticing your krill-iance!",
      "You're a krill-ionaire in knowledge!",
      "No one can catch this krill today!",
      "You're the biggest krill in the current!",
      "Krill-ing the competition! Literally.",
      "A krill-iant display of focus!"
    ],
    levelUp: "You've grown from a speck to a Krill! Watch out for whales!"
  },
  "Sea Snail": {
    moderate: [
      "Snailing it!",
      "Slow and steady progress!",
      "Leaving a trail of correct answers!",
      "You've got a shell of a lot of knowledge!",
      "Sliding through the material!",
      "Taking it one inch at a time!",
      "You're a snail on a mission!",
      "Don't be sluggish, keep going!",
      "A snail's pace is still a pace!",
      "You're carrying your study house with you!"
    ],
    high: [
      "The fastest snail in the sea!",
      "Turbo snail activated!",
      "You're leaving everyone in your slime!",
      "Snail-tastic! You're crushing it!",
      "A snail of pure genius!",
      "You're sliding past the competition!",
      "No salt can stop this snail!",
      "You've got the shell of a champion!",
      "Snail supreme! You're the best.",
      "The ocean bows to this turbo snail!"
    ],
    levelUp: "You're now a Sea Snail! Slow and steady wins the race!"
  },
  "Sardine": {
    moderate: [
      "Sardine-ing your way to the top!",
      "You're part of a smart school now!",
      "Swimming fast, Sardine! Keep it up.",
      "A silver flash of brilliance!",
      "You're not just another fish in the sea!",
      "Sardine strength! You're looking sharp.",
      "Keep schooling those questions!",
      "You're a sardine with a plan!",
      "Small fish, big dreams, huge progress!",
      "Sardine-sational work today!"
    ],
    high: [
      "You're leading the whole school now!",
      "A sardine storm of intelligence!",
      "You're too fast for any net to catch!",
      "Sardine-tastic! You're on fire!",
      "The smartest sardine in the Atlantic!",
      "You're packing a punch like a tin of sardines!",
      "A silver streak of study success!",
      "You're the sardine that whales fear!",
      "School's out, but you're still learning!",
      "Sardine supreme! You're the best."
    ],
    levelUp: "You're now a Sardine! You've joined the school of winners!"
  },
  "Seahorse": {
    moderate: [
      "Galloping through the seagrass of study!",
      "A majestic seahorse in its natural habitat!",
      "Slow and steady wins the race, Seahorse!",
      "You're a rare find in this ocean!",
      "Seahorse style! You're looking elegant.",
      "Keep your tail wrapped around those goals!",
      "You're a seahorse with serious skills!",
      "Trotting along to Step 2 success!",
      "A seahorse of a different color! Brilliant.",
      "Seahorse-ing around? No, you're working hard!"
    ],
    high: [
      "You're the fastest seahorse in the reef!",
      "A seahorse sprint! You're flying!",
      "You're a mythical creature of intelligence!",
      "Seahorse-tastic! You're crushing the goals!",
      "The most focused seahorse in the sea!",
      "You're galloping past the competition!",
      "A seahorse of pure genius!",
      "You've got the heart of a sea-stallion!",
      "Seahorse supreme! You're the champion.",
      "No one can rein in this seahorse!"
    ],
    levelUp: "Giddy up! You're now a Seahorse, galloping toward success!"
  },
  "Squid": {
    moderate: [
      "Inking your way to success!",
      "You're a squid with a plan!",
      "Ten tentacles of study power!",
      "Squid-tastic! Keep it up.",
      "You're looking sharp, Squid!",
      "Don't squirt ink, just answer questions!",
      "A squid of many talents!",
      "You're grabbing knowledge with all your arms!",
      "Squid power! You're on a roll.",
      "Keep swimming, you're doing great!"
    ],
    high: [
      "The smartest squid in the sea!",
      "A kraken of intelligence!",
      "You're inking all over the competition!",
      "Squid-tastic! You're unstoppable!",
      "A squid of pure genius!",
      "You're grabbing success with all ten arms!",
      "No one can catch this squid!",
      "You've got the brain of a giant squid!",
      "Squid supreme! You're the champion.",
      "The ocean bows to this kraken!"
    ],
    levelUp: "You're now a Squid! Inking your way through the tough stuff!"
  },
  "Pufferfish": {
    moderate: [
      "Puffing up with knowledge!",
      "Don't let the pressure get to you!",
      "You're a pufferfish with a purpose!",
      "Puffer-tastic! Keep it up.",
      "You're looking sharp, Pufferfish!",
      "A pufferfish of many talents!",
      "You're inflating your brain!",
      "Puffer power! You're on a roll.",
      "Keep swimming, you're doing great!",
      "Don't burst your bubble, keep studying!"
    ],
    high: [
      "The smartest pufferfish in the sea!",
      "A pufferfish of pure intelligence!",
      "You're puffing up past the competition!",
      "Puffer-tastic! You're unstoppable!",
      "A pufferfish of pure genius!",
      "You're inflating your success!",
      "No one can catch this pufferfish!",
      "You've got the brain of a giant pufferfish!",
      "Puffer supreme! You're the champion.",
      "The ocean bows to this pufferfish!"
    ],
    levelUp: "You're now a Pufferfish! Puffing up with knowledge!"
  },
  "Flying Fish": {
    moderate: [
      "Soaring above the waves of worry!",
      "You're taking flight, Flying Fish!",
      "A leap of faith into your studies!",
      "Flying Fish focus! You're looking sharp.",
      "Keep gliding toward that exam date!",
      "You're a fish with wings! Amazing.",
      "Flying high on those correct answers!",
      "A flying fish with a bright future!",
      "You're soaring past the average!",
      "Flying Fish-tastic! Keep it up."
    ],
    high: [
      "You're the highest flyer in the ocean!",
      "A supersonic flying fish! You're fast.",
      "You're soaring over every obstacle!",
      "Flying Fish-tastic! You're unstoppable!",
      "The most aerodynamic student in the sea!",
      "You're flying circles around the rest!",
      "A flying fish of pure brilliance!",
      "You've reached new heights today!",
      "Flying Fish supreme! You're the ace.",
      "The sky is the limit for this fish!"
    ],
    levelUp: "You've taken flight! You're now a Flying Fish, soaring above the rest!"
  },
  "Jellyfish": {
    moderate: [
      "Glowing with knowledge!",
      "You're a jellyfish with a mission!",
      "Stinging through these questions!",
      "Jellyfish-tastic! Keep it up.",
      "You're looking bright, Jellyfish!",
      "A jellyfish of many talents!",
      "You're paralyzing your goals!",
      "Jellyfish power! You're on a roll.",
      "Keep drifting, you're doing great!",
      "Don't get tangled, keep studying!"
    ],
    high: [
      "The smartest jellyfish in the sea!",
      "A jellyfish of pure intelligence!",
      "You're stinging past the competition!",
      "Jellyfish-tastic! You're unstoppable!",
      "A jellyfish of pure genius!",
      "You're glowing with success!",
      "No one can catch this jellyfish!",
      "You've got the brain of a giant jellyfish!",
      "Jellyfish supreme! You're the champion.",
      "The ocean bows to this jellyfish!"
    ],
    levelUp: "You're now a Jellyfish! You're glowing with knowledge!"
  },
  "Barracuda": {
    moderate: [
      "Sharp mind, sharp teeth, Barracuda!",
      "You're a predator of problems now!",
      "Barracuda bite! You're crushing it.",
      "A silver flash of study power!",
      "Keep hunting those high scores!",
      "You're a barracuda with a mission!",
      "Barracuda brilliance! You're looking fierce.",
      "No question is safe from your teeth!",
      "You're a barracuda on the prowl!",
      "Barracuda-tastic! Keep the pressure on."
    ],
    high: [
      "You're the apex predator of this reef!",
      "A barracuda blitz! You're terrifyingly smart.",
      "You're tearing through the material!",
      "Barracuda-tastic! You're the boss.",
      "The most lethal student in the ocean!",
      "You're hunting down success like a pro!",
      "A barracuda of pure genius!",
      "You've got the bite to back up the bark!",
      "Barracuda supreme! You're the king.",
      "No one dares challenge this barracuda!"
    ],
    levelUp: "Watch out! You're now a Barracuda, the sharpest mind in the sea!"
  },
  "Stingray": {
    moderate: [
      "Gliding effortlessly through the deep!",
      "You're a stingray with a plan!",
      "A majestic force of study power!",
      "Stingray-tastic! Keep it up.",
      "You're looking sharp, Stingray!",
      "A stingray of many talents!",
      "You're gliding past your goals!",
      "Stingray power! You're on a roll.",
      "Keep swimming, you're doing great!",
      "Don't bury yourself, keep studying!"
    ],
    high: [
      "The smartest stingray in the sea!",
      "A stingray of pure intelligence!",
      "You're gliding past the competition!",
      "Stingray-tastic! You're unstoppable!",
      "A stingray of pure genius!",
      "You're gliding to success!",
      "No one can catch this stingray!",
      "You've got the brain of a giant stingray!",
      "Stingray supreme! You're the champion.",
      "The ocean bows to this stingray!"
    ],
    levelUp: "You're now a Stingray! Gliding effortlessly through the deep!"
  },
  "Dolphin": {
    moderate: [
      "You're making a splash!",
      "You're a dolphin with a mission!",
      "Playful yet focused approach!",
      "Dolphin-tastic! Keep it up.",
      "You're looking sharp, Dolphin!",
      "A dolphin of many talents!",
      "You're leaping over your goals!",
      "Dolphin power! You're on a roll.",
      "Keep swimming, you're doing great!",
      "Don't just play around, keep studying!"
    ],
    high: [
      "The smartest dolphin in the sea!",
      "A dolphin of pure intelligence!",
      "You're leaping past the competition!",
      "Dolphin-tastic! You're unstoppable!",
      "A dolphin of pure genius!",
      "You're leaping to success!",
      "No one can catch this dolphin!",
      "You've got the brain of a giant dolphin!",
      "Dolphin supreme! You're the champion.",
      "The ocean bows to this dolphin!"
    ],
    levelUp: "You're now a Dolphin! You're the smartest mammal in the sea!"
  },
  "Orca": {
    moderate: [
      "A brilliant tactician of the sea!",
      "You're an orca with a plan!",
      "Dominating the question bank!",
      "Orca-tastic! Keep it up.",
      "You're looking sharp, Orca!",
      "An orca of many talents!",
      "You're dominating your goals!",
      "Orca power! You're on a roll.",
      "Keep swimming, you're doing great!",
      "Don't play with your food, keep studying!"
    ],
    high: [
      "The smartest orca in the sea!",
      "An orca of pure intelligence!",
      "You're dominating the competition!",
      "Orca-tastic! You're unstoppable!",
      "An orca of pure genius!",
      "You're dominating your success!",
      "No one can catch this orca!",
      "You've got the brain of a giant orca!",
      "Orca supreme! You're the champion.",
      "The ocean bows to this orca!"
    ],
    levelUp: "You're now an Orca! A brilliant tactician of the sea!"
  },
  "Great White Shark": {
    moderate: [
      "The king of the ocean is here!",
      "Shark style! You're looking dominant.",
      "Just keep swimming, just keep winning!",
      "A great white shark of intelligence!",
      "Keep biting into those difficult topics!",
      "You're a shark with a plan for success!",
      "Shark-tastic! You're the top dog.",
      "No exam can escape your jaws!",
      "You're a shark on a study streak!",
      "Great White greatness in the making!"
    ],
    high: [
      "You're the most feared student in the sea!",
      "A shark attack of pure brilliance!",
      "You're devouring the material today!",
      "Shark-tastic! You're the absolute legend.",
      "The ultimate predator of Step 2!",
      "You're at the top of the food chain!",
      "A great white of pure genius!",
      "You've got the power of the ocean!",
      "Shark supreme! You're the champion.",
      "The ocean bows to this great white!"
    ],
    levelUp: "Jaws-dropping! You're now a Great White Shark, the master of the deep!"
  },
  "Blue Whale": {
    moderate: [
      "A literal giant of medicine has arrived!",
      "Whale power! You're looking massive.",
      "You're the biggest brain in the sea!",
      "A blue whale of pure intelligence!",
      "Keep making those huge waves of progress!",
      "You're a whale with a heart of gold!",
      "Whale-tastic! You're the ultimate.",
      "No challenge is too big for you!",
      "You're a whale on a winning streak!",
      "Blue Whale brilliance at its finest!"
    ],
    high: [
      "You're the most majestic student in the world!",
      "A whale of a time with these questions!",
      "You're an ocean-sized genius today!",
      "Whale-tastic! You're the absolute GOAT.",
      "The biggest, smartest, best of all!",
      "You're making a splash heard 'round the world!",
      "A blue whale of pure, unadulterated genius!",
      "You've reached the pinnacle of progress!",
      "Whale supreme! You're the god of the sea.",
      "The entire ocean is yours, Blue Whale!"
    ],
    levelUp: "Incredible! You're now a Blue Whale, a literal giant of medicine!"
  }
};

export const DAILY_GOAL = 180;
export const MILESTONE_1 = 120;
/** Default Step 2 exam calendar day (local `YYYY-MM-DD`). */
export const DEFAULT_EXAM_DATE_KEY = '2026-05-30';
/** @deprecated Use persisted `examDateKey` / settings; kept as default fallback. */
export const EXAM_DATE = new Date(DEFAULT_EXAM_DATE_KEY + 'T12:00:00');
export const RECORD_DAY_MODAL_LAST_SHOWN_KEY = 'recordDayModalLastShownDate';
/** When `'true'`, first-launch onboarding has been completed or skipped. */
export const ONBOARDING_COMPLETE_STORAGE_KEY = 'onboardingComplete';
